# Translations template for pypowervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 0.0.3.dev270\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 13:53-0500\n"
"PO-Revision-Date: 2015-10-06 13:53-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: pypowervm/exceptions.py:116
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"無法衍生 WWPN %(wwpn)s 的適當實體 FC 埠。"
"「VIOS 延伸屬性群組」可能不足。VIOS URI"
"是 %(vio_uri)s。"

#: pypowervm/exceptions.py:122
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "找不到元素：%(element_type)s %(element)s"

#: pypowervm/exceptions.py:126
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "找不到 LPAR：%(lpar_name)s"

#: pypowervm/exceptions.py:130
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "'%(operation_name)s' 作業失敗。%(error)s"

#: pypowervm/exceptions.py:134
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"'%(operation_name)s' 作業失敗。無法在 %(seconds)d 秒內完成"
"作業。"

#: pypowervm/exceptions.py:139
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "無法關閉虛擬機器 %(lpar_nm)s 的電源：%(reason)s"

#: pypowervm/exceptions.py:143
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "無法開啟虛擬機器 %(lpar_nm)s 的電源：%(reason)s"

#: pypowervm/exceptions.py:147
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"無法移除 VLAN %(vlan_id)d，因為它是另一個網路橋接器上的"
"主要 VLAN ID。"

#: pypowervm/exceptions.py:152
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"無法供應 VLAN %(vlan_id)d。它似乎包含在"
"Virtual I/O Server %(vios)s 上的裝置 '%(dev_name)s' 中。該裝置"
"未連接至任何網路橋接器（共用乙太網路配接卡）。"
"請手動移除該裝置或將它新增至網路橋接器，然後再"
"繼續。"

#: pypowervm/exceptions.py:161
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"名為 %(lu_name)s 的邏輯單元已經存在於下列共用儲存區上："
"%(ssp_name)s。"

#: pypowervm/exceptions.py:166
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"找不到要將虛擬光纖通道埠對映至的實體埠。"
"這是由於 Virtual I/O Server 無法使用，或者"
"實體光纖通道埠的埠規格不適當。"

#: pypowervm/exceptions.py:173
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"無法將主控台啟動至虛擬機器。pypowervm API "
"正在以非本端模式執行。僅當 "
"pypowervm 與 PowerVM API 存在於相同位置時，才能部署主控台。"

#: pypowervm/exceptions.py:180
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s 沒有子作業！"

#: pypowervm/exceptions.py:184
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask 不能有空的資訊來源。"

#: pypowervm/exceptions.py:188
#, python-format
msgid "OS unable to read file %(access_file)s."
msgstr "作業系統無法讀取檔案 %(access_file)s。"

#: pypowervm/exceptions.py:192
#, python-format
msgid "OS able to read file %(access_file)s, but encountered an access error."
msgstr "作業系統能夠讀取檔案 %(access_file)s，但遇到存取錯誤。"

#: pypowervm/exceptions.py:197
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "移轉作業失敗。%(error)s"

#: pypowervm/exceptions.py:201
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "找不到 VM %(vm_name)s 的載入來源"

#: pypowervm/util.py:122
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"所提出的延伸屬性群組 '%(arg_xag)s' 與下列現有延伸屬性群組不符："
"'%(path_xag)s'"

#: pypowervm/util.py:391
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "字首及字尾總共不能超過 %d 個字元。"

#: pypowervm/util.py:396
msgid "Total length must be at least 1 character."
msgstr "總長度必須至少是 1 個字元。"

#: pypowervm/util.py:419
msgid "The name parameter must be at least one character long."
msgstr "名稱參數的長度必須至少是一個字元。"

#: pypowervm/util.py:422
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "當 trunk_ok 為 False 時，名稱參數不得超過 %d 個字元。"

#: pypowervm/helpers/log_helper.py:82
#, python-format
msgid "REQUEST: %s"
msgstr "要求：%s"

#: pypowervm/helpers/log_helper.py:102
#, python-format
msgid "RESPONSE: %s"
msgstr "回應：%s"

#: pypowervm/tasks/cna.py:77
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "在系統上找不到虛擬交換器 %s。"

#: pypowervm/tasks/hdisk.py:182
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"硬碟探索失敗；將清除 LPAR ID %s 的陳舊儲存體，"
"然後重試。"

#: pypowervm/tasks/hdisk.py:324
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "LUA 回復成功。找到裝置：%s"

#: pypowervm/tasks/hdisk.py:328
#, python-format
msgid "ITL Error encountered: %s"
msgstr "遇到 ITL 錯誤：%s"

#: pypowervm/tasks/hdisk.py:330
#, python-format
msgid "%s Device is currently in use."
msgstr "%s 裝置目前在使用中。"

#: pypowervm/tasks/hdisk.py:332
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "探索到 %s 裝置具有不明 UDID。"

#: pypowervm/tasks/hdisk.py:334
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "無法探索裝置：%s"

#: pypowervm/tasks/hdisk.py:404
#, python-format
msgid "CLIRunner Error: %s"
msgstr "CLIRunner 錯誤：%s"

#: pypowervm/tasks/memory.py:101
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"取得 UUID 為 '%(host)s' 之主機的主機記憶體開銷時發生錯誤："
"%(error)s。"

#: pypowervm/tasks/power.py:159 pypowervm/tasks/power.py:168
#, python-format
msgid "Error: %s"
msgstr "錯誤：%s"

#: pypowervm/tasks/power.py:200
#, python-format
msgid ""
"Error invalidating adapter cache for LPAR  %(lpar_name) with UUID "
"%(lpar_uuid)s: %(exc)s"
msgstr ""
"讓具有下列 UUID 的 LPAR  %(lpar_name) 的配接卡快取失效時發生錯誤："
"%(lpar_uuid)s：%(exc)s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "正在重試修改 SCSI 對映。"

#: pypowervm/tasks/scsi_mapper.py:89
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"找到 %(stg_type)s 儲存體元素 %(stg_name)s 的現有對映：從"
"Virtual I/O Server %(vios_name)s 至用戶端 LPAR %(lpar_uuid)s。"

#: pypowervm/tasks/scsi_mapper.py:107
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"正在建立 %(stg_type)s 儲存體元素 %(stg_name)s 的對映：從"
"Virtual I/O Server %(vios_name)s 至用戶端 LPAR %(lpar_uuid)s。"

#: pypowervm/tasks/scsi_mapper.py:371
msgid "Must not specify both match_func and stg_elem."
msgstr "不得同時指定 match_func 和 stg_elem。"

#: pypowervm/tasks/storage.py:287
#, python-format
msgid "Unable to cleanup after file upload. File uuid: %s"
msgstr "上傳檔案之後無法清除。檔案 UUID：%s"

#: pypowervm/tasks/storage.py:385
#, python-format
msgid ""
"Linked clone Logical Unit %(luname)s (UDID %(udid)s) has no backing image"
" LU.  It should probably be deleted."
msgstr ""
"鏈結複本邏輯單元 %(luname)s (UDID %(udid)s) 沒有支持的映像檔"
"LU。它可能已被刪除。"

#: pypowervm/tasks/storage.py:430
msgid "Unable to locate new vDisk on file upload."
msgstr "在檔案上傳時，找不到新的 vDisk。"

#: pypowervm/tasks/storage.py:480
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "正在從磁區群組 %(vg)s 刪除虛擬磁碟 %(vdisk)s"

#: pypowervm/tasks/storage.py:504
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "正在從磁區群組 %(vg)s 刪除虛擬光學裝置 %(vopt)s"

#: pypowervm/tasks/storage.py:559
#, python-format
msgid "Removing LU %(lu_name)s from SSP %(ssp_name)s"
msgstr "正在從 SSP %(ssp_name)s 移除 LU %(lu_name)s"

#: pypowervm/tasks/storage.py:580
#, python-format
msgid ""
"Removing Image LU %(lu_name)s from SSP %(ssp_name)s because it is no "
"longer in use."
msgstr ""
"正在從 SSP %(ssp_name)s 移除映像檔 LU %(lu_name)s，因為該 LU 不再"
"處於使用中狀態。"

#: pypowervm/tasks/storage.py:625
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"正在將 %(num_maps)d 個孤立 %(stg_type)s 對映從 VIOS "
"%(vios_name)s 中移除。"

#: pypowervm/tasks/storage.py:652
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"正在將 %(num_maps)d 個與 LPAR ID "
"%(lpar_id)d 相關聯的 %(stg_type)s 對映從 VIOS %(vios_name)s 中移除。"

#: pypowervm/tasks/storage.py:725
#, python-format
msgid "Unexpected storage element type %s."
msgstr "非預期的儲存體元素類型 %s。"

#: pypowervm/tasks/storage.py:742
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"正在從 VIOS %(vios)s 清除以下 %(vdcount)d 個虛擬磁碟："
"%(vdlist)s"

#: pypowervm/tasks/storage.py:750
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"正在從 VIOS %(vios)s 清除以下 %(vocount)d 個虛擬光學裝置："
"%(volist)s"

#: pypowervm/tasks/storage.py:814
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"正在從 VIOS %(vios_name)s 跳過下列 LPAR ID 的 %(stg_type)s 對映清除，"
"原因是已存在這些 LPAR：%(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:379
#, python-format
msgid "Detected a stale mapping for LPAR with UUID %s."
msgstr "偵測到 LPAR（UUID 為 %s）的陳舊對映。"

#: pypowervm/tasks/vfc_mapper.py:583
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"找不到適當的 VIOS。提供的有效負載可能"
"不足。有效負載資料為：\n"
"%s"

#: pypowervm/tasks/vterm.py:61
msgid "Unable to close vterm."
msgstr "無法關閉 vterm。"

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "這是測試"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "一則訊息，針對此訊息不存在轉換"

#: pypowervm/utils/retry.py:152
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"對 URI %(uri)s 嘗試第 %(retry)d 次（總計 %(total)d 次）。錯誤是一個已知的"
"重試回應碼：%(resp_code)s"

#: pypowervm/utils/retry.py:159
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"第 %(retry)d 次嘗試（共 %(total)d 次）失敗。將重試。異常狀況為：\n"
"%(except)s。"

#: pypowervm/utils/transaction.py:311
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "必須提供 EntryWrapper 或 EntryWrapperGetter。"

#: pypowervm/utils/transaction.py:337
msgid "Must supply a valid Subtask."
msgstr "必須提供有效的子作業。"

#: pypowervm/utils/transaction.py:341
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "「提供項目」名稱 %s 重複。"

#: pypowervm/utils/transaction.py:416
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask  %s 沒有子作業；沒有作業執行。"

#: pypowervm/utils/transaction.py:541
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "必須提供 EntryWrapper 的清單，或者提供 FeedGetter。"

#: pypowervm/utils/transaction.py:720
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s 沒有子作業；沒有作業執行。"

#: pypowervm/utils/validation.py:160
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"針對下列虛擬機器，主機上可用的 %(res_name)s 不足："
"'%(instance_name)s'（要求 %(requested)s 個，但只有 %(avail)s 個可用）"

#: pypowervm/utils/validation.py:187
msgid "memory"
msgstr "記憶體）"

#: pypowervm/utils/validation.py:207
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"記憶體下限或上限。請先關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:292
msgid "CPUs"
msgstr "CPU 數目"

#: pypowervm/utils/validation.py:308
msgid "processing units"
msgstr "處理裝置數目"

#: pypowervm/utils/validation.py:349
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"處理器數目下限或上限。請先關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"處理器單元數目下限或上限。請先關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:375
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"處理器相容模式。請先關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:383
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"處理模式。請先關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:412
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"想要的處理器數目 (%(vcpus)d) 不能超過"
"虛擬機器 '%(instance_name)s' 之每個分割區容許的處理器數目上限"
"(%(max_allowed)d)。"

#: pypowervm/utils/validation.py:424
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"處理器數目上限 (%(vcpus)d) 不得超過"
"虛擬機器 '%(instance_name)s' 的系統容量處理器上限"
"(%(max_allowed)d)。"

#: pypowervm/utils/validation.py:442
#, python-format
msgid "The shared processor pool for %s must be DefaultPool."
msgstr "%s 的共用處理器儲存區必須是 DefaultPool。"

#: pypowervm/utils/validation.py:450
#, python-format
msgid "The shared processor pool for %s cannot be changed."
msgstr "無法變更 %s 的共用處理器儲存區。"

#: pypowervm/utils/validation.py:513
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"簡化的遠端重新啟動功能。請先關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/wrappers/base_partition.py:470
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos '%s' 無效。"

#: pypowervm/wrappers/entry_wrapper.py:258
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "在物件 %(pvmobject)s 中，無法轉換 %(property_name)s='%(value)s'"

#: pypowervm/wrappers/entry_wrapper.py:337
#, python-format
msgid "The expected parameter of %(param)s was not found in %(identifier)s"
msgstr "在 %(identifier)s 中找不到預期的參數 %(param)s"

#: pypowervm/wrappers/entry_wrapper.py:386
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"拒絕透過多重鏈結設定 href。\n"
"路徑：%{path}s\n"
"找到的鏈結數目：%{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:430
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "拒絕建構及覆蓋不含標記的元素。"

#: pypowervm/wrappers/entry_wrapper.py:554
msgid "Response is missing 'entry' property."
msgstr "回應遺漏了 'entry' 內容。"

#: pypowervm/wrappers/entry_wrapper.py:568
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "必須提供 Response 或 Entry 才能覆蓋。取得 %s"

#: pypowervm/wrappers/entry_wrapper.py:667
msgid "Parent UUID specified without parent type."
msgstr "指定的母項 UUID 不含親項類型。"

#: pypowervm/wrappers/entry_wrapper.py:670
msgid "The search() method requires exactly one key=value argument."
msgstr "search() 方法只需要一個 key=value 引數。"

#: pypowervm/wrappers/entry_wrapper.py:698
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "封套類別 %(class)s 不支援搜尋關鍵字 '%(key)s'。"

#: pypowervm/wrappers/entry_wrapper.py:774
msgid "Must specify both parent type and UUID, or neither."
msgstr "必須同時指定親項類型及 UUID，或者都不指定。"

#: pypowervm/wrappers/entry_wrapper.py:851
msgid "Cannot set uuid."
msgstr "無法設定 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:1041
msgid "No such child element."
msgstr "沒有此類子元素。"

#: pypowervm/wrappers/entry_wrapper.py:1102
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "無法在沒有 meta 資料的封套上設定 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:1107
#, python-format
msgid "uuid value not valid: %s"
msgstr "UUID 值無效：%s"

#: pypowervm/wrappers/entry_wrapper.py:1155
msgid "Must specify a Wrapper subclass."
msgstr "必須指定封套子類別。"

#: pypowervm/wrappers/entry_wrapper.py:1162
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "必須同時指定母類別及母項 UUID，或者兩者皆不指定。"

#: pypowervm/wrappers/job.py:281
#, python-format
msgid "Job %(job_id)s failed to cancel after %(timeout)s seconds."
msgstr "在 %(timeout)s 秒之後，無法取消工作 %(job_id)s。"

#: pypowervm/wrappers/job.py:302
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "未刪除工作 %s。工作處於執行中狀態。"

#: pypowervm/wrappers/logical_partition.py:139
#: pypowervm/wrappers/logical_partition.py:208
msgid "LPAR does not have an active RMC connection."
msgstr "LPAR 沒有作用中的 RMC 連線。"

#: pypowervm/wrappers/logical_partition.py:141
#, python-format
msgid "LPAR does not have an active DLPAR capability for %s."
msgstr "LPAR 沒有作用中的 DLPAR 功能適用於 %s。"

#: pypowervm/wrappers/logical_partition.py:153
msgid "I/O"
msgstr "I/O"

#: pypowervm/wrappers/logical_partition.py:163
msgid "Memory"
msgstr "記憶體"

#: pypowervm/wrappers/logical_partition.py:173
msgid "Processors"
msgstr "處理器數目"

#: pypowervm/wrappers/logical_partition.py:190
msgid "LPAR is not in an active state."
msgstr "LPAR 未處於作用中狀態。"

#: pypowervm/wrappers/logical_partition.py:196
msgid "IBM i LPAR does not have restricted I/O."
msgstr "IBM i LPAR 沒有受限的 I/O。"

#: pypowervm/wrappers/logical_partition.py:200
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "來源系統沒有 IBM i LPAR 行動性功能。"

#: pypowervm/wrappers/logical_partition.py:205
msgid "IBM i LPAR Live Migration is only supported on POWER7 and higher systems."
msgstr "IBM i LPAR 即時移轉只在 POWER7 及更高系統上受支援。"

#: pypowervm/wrappers/logical_partition.py:212
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "由於遺漏 DLPAR 功能，LPM 無法使用 LPAR。"

#: pypowervm/wrappers/logical_partition.py:273
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc '%s' 無效。"

#: pypowervm/wrappers/storage.py:437
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV 具有已編碼的 pg83 描述子 \"%(pg83_raw)s\"，但無法解碼 "
"(%(type_error)s)。"

